apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yaml convert
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: employeesusvc
  name: employeesusvc
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: employeesusvc
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yaml convert
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/compose2-default: "true"
        io.kompose.service: employeesusvc
    spec:
      containers:
        - image: mikolajuaim/application:ssjw-eautoservice-employeesusvc
          name: employeesusvc
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
