apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yaml convert
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: webclientapplication
  name: webclientapplication
spec:
  type: NodePort
  ports:
    - name: "5000"
      port: 80
      targetPort: 80
      nodePort: 30081
  selector:
    io.kompose.service: webclientapplication
status:
  loadBalancer: {}
